### ISSUE TITLE
BUG: can't select text on mobile

### ISSUE THREAD

**Issue by fplord** [igneous-labs/omnispace#40]
reply long press overrides text selection on mobile so we cant select part of or all of a message to e.g. copy and paste to someone else

**Comment by Johnnycus** [comment]
same on web.telegram on mobile. if we add reply menu on long press there is no way to select a part of text, we can add "copy' button below reply though

**Comment by fplord** [comment]
> same on web.telegram on mobile. if we add reply menu on long press there is no way to select a part of text, we can add "copy' button below reply though

on Telegram Android mobile a single touch (no need long press) brings up a context menu

**Comment by fplord** [comment]
> > same on web.telegram on mobile. if we add reply menu on long press there is no way to select a part of text, we can add "copy' button below reply though
> 
> on Telegram Android mobile a single touch (no need long press) brings up a context menu

https://user-images.githubusercontent.com/97802371/221478179-b0ff25d2-d8b9-485b-89fd-5ef6d0a50fa7.mp4

**Comment by Johnnycus** [comment]
thats an app though, i was talking about the web.telegram.org

**Comment by Johnnycus** [comment]
https://github.com/igneous-labs/omnispace/pull/71
