### ISSUE TITLE
FEAT: desktop should be a 2 column view

### ISSUE THREAD

**Issue by fplord** [igneous-labs/omnispace#50]
Current:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/97802371/221481328-085a984c-035f-4d81-810d-cb7f27b46425.png">

Potential:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/97802371/221481623-fea26918-d117-4a6a-8213-c9a674a88500.png">

**Comment by billythedummy** [comment]
set app div to flex-row + flex-wrap

**Comment by fplord** [comment]
> set app div to flex-row + flex-wrap

see latest changes in master
